<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Online Users</strong> Module Configuration' => '',
    'Back to modules' => '',
    'From which registration date should new users displayed as new?' => '',
    'Save' => '',
    'The number of online users that will be shown.' => '',
    'The panel title for the dashboard widget.' => '',
    'This value is maybe necessary after an import from existing users. Let it empty if your user base grows naturally.' => '',
];
